name: Cross-compile Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-mac:
    runs-on: macos-latest

    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Install cross
        run: |
          curl -LSfs https://japaric.github.io/trust/install.sh | \
          sh -s -- --git cross-rs/cross --tag v0.2.2 -y

      - name: Build
        run: |
          cross build --target ${{ matrix.target }} --release

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ env.PROJECT_NAME }}

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-msvc
          - aarch64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Install cross
        run: |
          curl -LSfs https://japaric.github.io/trust/install.sh | \
          sh -s -- --git cross-rs/cross --tag v0.2.2 -y

      - name: Build
        run: |
          cross build --target ${{ matrix.target }} --release

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ env.PROJECT_NAME }}
